import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import Chart from 'chart.js/auto';
import { UserNode } from '../model/user';
import { calculateGhostScore } from './ghostScore';

export const generateHealthReportPDF = async (
  nonFollowers: readonly UserNode[],
  whitelisted: readonly UserNode[],
) => {
  // 1. Inicializar el documento PDF (Formato A4)
  const doc = new jsPDF();
  const dateStr = new Date().toLocaleDateString();

  // 2. Cálculos de Salud de la Cuenta
  let bots = 0;
  let ghosts = 0;
  let suspicious = 0;
  let safe = 0;

  const analyzedUsers = nonFollowers.map(user => {
    const analysis = calculateGhostScore(user);

    if (analysis.level === 'bot') {
      bots++;
    } else if (analysis.level === 'ghost') {
      ghosts++;
    } else if (analysis.level === 'suspicious') {
      suspicious++;
    } else {
      safe++;
    }

    return { user, analysis };
  });

  analyzedUsers.sort((a, b) => b.analysis.score - a.analysis.score);

  // --- 3. GENERAR GRÁFICA DONUT CON CHART.JS EN MEMORIA ---

  // Creamos un canvas virtual
  const canvas = document.createElement('canvas');
  canvas.width = 400;
  canvas.height = 400;
  canvas.style.display = 'none'; // Lo ocultamos de la vista
  document.body.appendChild(canvas);

  // Instanciamos Chart.js
  const chart = new Chart(canvas, {
    type: 'doughnut',
    data: {
      labels: ['Safe', 'Suspicious', 'Ghosts', 'Bots'],
      datasets: [
        {
          data: [safe, suspicious, ghosts, bots],
          backgroundColor: ['#4ade80', '#fbbf24', '#f87171', '#ef4444'], // Colores del semáforo
          borderWidth: 0,
        },
      ],
    },
    options: {
      animation: false, // ¡Crucial! Desactiva la animación para capturarlo instantáneamente
      responsive: false,
      plugins: {
        legend: {
          position: 'right',
          labels: { font: { size: 14 } },
        },
      },
    },
  });

  // Extraemos la imagen de la gráfica en Base64
  const chartImageBase64 = chart.toBase64Image();

  // Limpiamos la memoria destruyendo la gráfica y el canvas
  chart.destroy();
  document.body.removeChild(canvas);

  // --- 4. DISEÑO DEL PDF ---

  // Título Principal
  doc.setFontSize(22);
  doc.setTextColor(6, 182, 212); // Cyan primario
  doc.text('Instagram Community Health Report', 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${dateStr}`, 14, 28);
  doc.text('Generated by: Instagram Unfollowers PRO', 14, 33);

  // Sección de Resumen
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Account Overview', 14, 45);

  doc.setFontSize(11);
  doc.text(`Total Non-Followers Analyzed: ${nonFollowers.length}`, 14, 55);
  doc.text(`Protected Users (Whitelist): ${whitelisted.length}`, 14, 62);
  doc.text(
    `Account Breakdown: ${safe} Safe | ${suspicious} Suspicious | ${ghosts} Ghosts | ${bots} Bots`,
    14,
    69,
  );

  // Alerta de Salud
  doc.setFontSize(12);
  const totalRisky = bots + ghosts;
  const riskyPercentage =
    nonFollowers.length > 0 ? Math.round((totalRisky / nonFollowers.length) * 100) : 0;

  if (riskyPercentage > 30) {
    doc.setTextColor(239, 68, 68); // Rojo
    doc.text(
      `⚠️ Warning: ${riskyPercentage}% of your non-followers show bot or ghost activity.`,
      14,
      79,
    );
  } else {
    doc.setTextColor(34, 197, 94); // Verde
    doc.text(`✅ Your account is relatively healthy (${riskyPercentage}% ghost accounts).`, 14, 79);
  }

  // --- INSERTAR GRÁFICA EN EL DOCUMENTO ---
  // Formato: addImage(imageData, format, x, y, width, height)
  doc.addImage(chartImageBase64, 'PNG', 110, 35, 80, 80);

  // --- TABLA DE AUDITORÍA (Los peores primero) ---
  const tableData = analyzedUsers
    .slice(0, 100)
    .map(item => [
      `@${item.user.username}`,
      item.analysis.score.toString(),
      item.analysis.level.toUpperCase(),
      item.analysis.reasons.join(', '),
    ]);

  autoTable(doc, {
    startY: 120, // Bajamos la tabla para que no pise la gráfica de arriba
    head: [['Username', 'Risk Score', 'Classification', 'Detected Flags']],
    body: tableData,
    headStyles: { fillColor: [6, 182, 212] },
    alternateRowStyles: { fillColor: [241, 245, 249] },
    margin: { top: 10 },
  });

  // 5. Guardar el archivo localmente
  const filename = `IG_Health_Report_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
};
